import type { User, Question, Answer, Comment } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    avatarUrl: 'https://picsum.photos/seed/1/200/200',
    role: 'student',
    department: 'Computer Science',
    year: 2,
    bio: 'Aspiring full-stack developer with a passion for React and TypeScript.',
    skills: ['React', 'TypeScript', 'Node.js', 'Next.js'],
    reputation: 150,
    createdAt: '2023-01-15T09:30:00Z',
  },
  {
    id: 'user-2',
    name: 'Bob Williams',
    email: 'bob@example.com',
    avatarUrl: 'https://picsum.photos/seed/2/200/200',
    role: 'student',
    department: 'Electrical Engineering',
    year: 3,
    bio: 'Interested in embedded systems and IoT.',
    skills: ['C++', 'Python', 'Arduino', 'VHDL'],
    reputation: 95,
    createdAt: '2023-02-20T14:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    avatarUrl: 'https://picsum.photos/seed/3/200/200',
    role: 'teacher',
    department: 'Computer Science',
    bio: 'Professor specializing in algorithms and data structures.',
    skills: ['Algorithms', 'Data Structures', 'Java', 'Python', 'AI'],
    reputation: 1250,
    createdAt: '2022-08-10T11:45:00Z',
  },
  {
    id: 'user-4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    avatarUrl: 'https://picsum.photos/seed/4/200/200',
    role: 'student',
    department: 'Mechanical Engineering',
    year: 4,
    bio: 'Robotics enthusiast and CAD designer.',
    skills: ['SolidWorks', 'AutoCAD', 'MATLAB', 'Robotics'],
    reputation: 210,
    createdAt: '2023-03-05T18:20:00Z',
  },
    {
    id: 'user-6',
    name: 'Admin User',
    email: 'admin@example.com',
    avatarUrl: 'https://picsum.photos/seed/6/200/200',
    role: 'admin',
    department: 'Administration',
    bio: 'System administrator for NexusLearn.',
    skills: ['System Admin', 'Next.js', 'MongoDB'],
    reputation: 9999,
    createdAt: '2022-01-01T00:00:00Z',
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q-1',
    title: 'How to vertically align a div in CSS?',
    description: 'I\'ve been trying to vertically align a div inside another div for hours. I\'ve tried `vertical-align: middle`, `margin: auto`, and `position: absolute` with transforms, but nothing seems to work consistently across browsers. What is the modern, most reliable way to achieve this? I am using Flexbox.',
    tags: ['css', 'flexbox', 'layout'],
    authorId: 'user-1',
    createdAt: '2023-10-26T10:00:00Z',
    updatedAt: '2023-10-26T11:30:00Z',
    isSolved: true,
    acceptedAnswerId: 'ans-1',
    views: 1250,
    upvotes: 45,
    downvotes: 2,
  },
  {
    id: 'q-2',
    title: 'What is the difference between `let`, `const`, and `var` in JavaScript?',
    description: 'I\'m new to JavaScript (coming from Python) and I\'m confused about the three ways to declare variables. When should I use `let`, `const`, or `var`? What are the key differences in terms of scope and hoisting? An explanation with examples would be great.',
    tags: ['javascript', 'es6', 'variables', 'scope'],
    authorId: 'user-2',
    createdAt: '2023-10-25T14:20:00Z',
    updatedAt: '2023-10-25T14:20:00Z',
    isSolved: false,
    views: 890,
    upvotes: 78,
    downvotes: 1,
  },
  {
    id: 'q-3',
    title: 'Best way to handle authentication in a Next.js 14 App Router application?',
    description: 'I am building a new project with Next.js 14 and the App Router. What is the current best practice for handling user authentication? Should I use NextAuth.js, Clerk, Lucia, or roll my own with server components and actions? I need both social logins and email/password.',
    tags: ['next.js', 'authentication', 'app-router'],
    authorId: 'user-4',
    createdAt: '2023-10-27T08:00:00Z',
    updatedAt: '2023-10-27T08:00:00Z',
    isSolved: false,
    views: 340,
    upvotes: 22,
    downvotes: 0,
  },
];

export const mockAnswers: Answer[] = [
  {
    id: 'ans-1',
    questionId: 'q-1',
    authorId: 'user-3',
    content: "The modern and most robust way to vertically center a child element within a parent is using Flexbox. Set `display: flex;` on the parent container, and then `align-items: center;`. \n\n```css\n.parent {\n  display: flex;\n  align-items: center;\n  justify-content: center; /* For horizontal centering */\n  height: 300px; /* Or any height */\n}\n```\n\nThis method is highly reliable and avoids the complexities of older techniques.",
    createdAt: '2023-10-26T10:15:00Z',
    updatedAt: '2023-10-26T10:15:00Z',
    upvotes: 112,
    downvotes: 3,
  },
  {
    id: 'ans-2',
    questionId: 'q-2',
    authorId: 'user-3',
    content: "Great question! Here's a breakdown:\n\n- **`var`**: Function-scoped and hoisted. It's the old way and generally avoided now due to unpredictable behavior.\n- **`let`**: Block-scoped (`{...}`). It's hoisted but not initialized, so you can't access it before declaration (this is called the Temporal Dead Zone).\n- **`const`**: Also block-scoped, like `let`. The key difference is that its value cannot be *re-assigned* after declaration. The variable itself is not immutable if it's an object or array, meaning you can change its properties or elements.\n\n**Rule of thumb:** Default to `const`. If you know the variable needs to be reassigned, use `let`. Avoid `var`.",
    createdAt: '2023-10-25T14:35:00Z',
    updatedAt: '2023-10-25T14:35:00Z',
    upvotes: 98,
    downvotes: 0,
  },
  {
    id: 'ans-3',
    questionId: 'q-1',
    authorId: 'user-2',
    content: "You can also use CSS Grid, which is another powerful modern layout system. \n\n```css\n.parent {\n  display: grid;\n  place-items: center;\n  height: 300px;\n}\n```\n`place-items: center;` is a shorthand for `align-items: center;` and `justify-items: center;`. It's very concise!",
    createdAt: '2023-10-26T10:25:00Z',
    updatedAt: '2023-10-26T10:25:00Z',
    upvotes: 34,
    downvotes: 5,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'com-1',
    answerId: 'ans-1',
    authorId: 'user-1',
    content: 'Wow, this is exactly what I needed. So simple! Thanks, Professor!',
    createdAt: '2023-10-26T10:20:00Z',
  },
  {
    id: 'com-2',
    answerId: 'ans-2',
    authorId: 'user-2',
    content: 'The "Temporal Dead Zone" was the term I was looking for. This makes so much more sense now.',
    createdAt: '2023-10-25T15:00:00Z',
  },
];

export const mockTags: string[] = ['css', 'flexbox', 'layout', 'javascript', 'es6', 'variables', 'scope', 'next.js', 'authentication', 'app-router', 'react', 'typescript', 'node.js', 'python', 'java'];
